//TODO: https://github.com/davibaltar/swagger-autogen/issues/35
const swaggerAutogen = require("swagger-autogen")();

import { config } from "#/config/constants";
import fixtures from "#/config/server/fixtures.json";

const doc = {
  info: {
    version: "1.0.0",
    title: "Node API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${config.serverPort}`,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Organization",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description...",
    },
  },
  definitions: {
    Entity: {
      ...fixtures.service.organization.entity,
    },
  },
};

const basePath = (path: string) =>
  config.script === "swagger" ? `dist/src/${path}.js` : `src/${path}.ts`;

const outputFile = "./swagger.json";
const endpointsFiles = [basePath("app")];

(async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc);
})();
